on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Mod
        uses: geode-sdk/build-geode@v2.1.0 
        with:
          bindings-version: 'v2.0.0-beta.1'
          platform: ANDROID

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: layout-up-mod
          path: "**/*.geode"
